version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: first_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "qpflxktm(*)!#%"
      MYSQL_DATABASE: first_ent
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:


# Run Once when init project